version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: roots/wordpress
    versions:
    - 5.6.1
    - 5.6.2
    - "5.7"
  - dependency-name: composer/installers
    versions:
    - 1.10.0
